### ISSUE TITLE
An inquiry about the total Lagrangian formulation implementation in MSC.MARC with DAMASK

### ISSUE THREAD

**Issue by NINGYURICHARD** [damask-multiphysics/DAMASK#22]
Hi,

I found DAMASK can handle CPFEM with MSC.MARC  in an updated Lagrangian setting. May I ask whether DAMASK-MSC.MARC supports total Lagrangian formulation? 

I noticed the document of MSC.MARC (Volume D: User Subroutines and Special Routines), we can choose 'LARGE DISP' flag for total Lagrangian formulation and 'UPDATE' flag for updated Lagrangian formulation. So I think we can also implement the total Lagrangian formulation in DAMASK theoretically.

Regards,
Richard

**Comment by MarDiehl** [comment]
we only have the current implementation.

**Comment by FranzRoters** [comment]
One could certainly implement it, but why?

Do you see any specific advantage in a total Lagrangian formulation?
